### ISSUE TITLE
您好，运行失败

### ISSUE THREAD

**Issue by superwei629** [EnDragon/EDragon_TiebaBackup#1]
请问是否可以直接打包出来,供下载

**Comment by EnDragon** [comment]
百度贴吧最近貌似好像加上更多的反爬虫的机制了，不知道为什么我在城市里的时候运行V0.8.8版本没有任何问题，在老家运行V0.8.8版本会出现需要等一段时间才能相应的情况，最近我真的没时间了(我是高三的学生，马上要高考了，没有精力负责这些了)


V0.8.8的原版：

https://pan.baidu.com/s/1qPEMAL8baSNFXDtU3L06XA&nbsp;
提取码：j1dm&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EnDragon/EDragon_TiebaBackup"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午4:33
收件人:&nbsp;"EnDragon/EDragon_TiebaBackup"<EDragon_TiebaBackup@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EnDragon/EDragon_TiebaBackup] 您好，运行失败 (#1)





 
请问是否可以直接打包出来,供下载

**Comment by EnDragon** [comment]
百度贴吧最近貌似好像加上更多的反爬虫的机制了，不知道为什么我在城市里的时候运行V0.8.8版本没有任何问题，在老家运行V0.8.8版本会出现需要等一段时间才能响应的情况，最近我真的没时间了(我是高三的学生，马上要高考了，没有精力负责这些了)


V0.8.8的原版：

https://pan.baidu.com/s/1qPEMAL8baSNFXDtU3L06XA 
提取码：j1dm 



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "EnDragon/EDragon_TiebaBackup"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午4:33
收件人:&nbsp;"EnDragon/EDragon_TiebaBackup"<EDragon_TiebaBackup@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EnDragon/EDragon_TiebaBackup] 您好，运行失败 (#1)





 
请问是否可以直接打包出来,供下载
